version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: helloworld
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    image: php:8.2.18-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    environment:
        XDEBUG_CONFIG: client_host=host.docker.internal
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
